services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "dev"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s # Optional: give the container time to initialize

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"  # Redis server
      - "8001:8001"  # RedisInsight (or 5540:5540 for newer versions if 8001 doesn't work)
    volumes:
      - ./data/redis:/data

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - localpaas
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - localpaas
    restart: unless-stopped

networks:
  localpaas:
    driver: bridge
# volumes:
#   mysqldb:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "./data/mysql"
#   mongodb:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "./data/mongo"
#   postgresdb:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "./data/postgres"
#   pgadmindb:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "./data/pgadmin"
#   redisdb:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "./data/redis"
