services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379"  # Redis server
      - "8001:8001"  # RedisInsight (or 5540:5540 for newer versions if 8001 doesn't work)
    volumes:
      - ./data/redis_data:/data
